version: '2'
services:

  app:
    build: app
    ports:
      - "8000:80"
    links:
      - mysql
      - postgres
    depends_on:
      - mysql
      - postgres

  mail:
    image: catatnight/postfix
    ports:
      - "25:25"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ''


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: 'mysql'
    depends_on:
      - mysql

  phppgadmin:
    image: jacksoncage/phppgadmin
    ports:
      - "8002:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: 'postgres'


